version: 2.1
jobs:
  build:
    docker:
      - image: circleci/php:7.4-fpm-node-browsers
    steps:
      - checkout
      - run: composer install -n --prefer-dist
      - run: npm ci
      - run: npm run dev
      - run:
        name: php test
        command: ./vendor/bin/phpunit
